
<form action="" method = "post" class="action">
    <legend>
        <h3>Register</h3>
    </legend>
    <label for="username"> Username</label>
    <input type="text" name = "username" id="username">
    <label for="email"> email</label>
    <input type="email" name = "email" id="email">
    <label for="password"> Password</label>
    <input type="password" name = "password" id="password">
    <label for="password2"> Password confirmation</label>
    <input type="password" name = "password2" id="password2">
    <button type="submit">Send</button>
</form>
